pipeline:
  phpunit-test:
    image: nextcloudci/php7.0:php7.0-2
    environment:
    - APP_NAME=circles
    - CORE_BRANCH=shares-circles
    - DB=sqlite
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml


