name: Static analysis

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  static-psalm-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ocp-version: [ 'dev-stable26' ]

    name: Nextcloud ${{ matrix.ocp-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: Install dependencies
        run: composer require --dev christophwurst/nextcloud:${{ matrix.ocp-version }}

      - name: Run coding standards check
        run: composer run psalm
